version: '3.8'

services:
  authenticationservice:
    image: rasmusdd/authenticationservice-image:latest
    ports:
      - 82:8080
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - ConnectionString=mongodb://admin:1234@userservice:27017/4SemProj
      - DatabaseName=4SemProj
      - collectionName=Bruger
    container_name: authenticationservice
    hostname: authenticationservice
    networks:
      - auctionnetwork
    command: ["/bin/sh", "-c", "sleep 20 && dotnet Authentication.dll"]

  userservice:
    image: jakobhaulund/bruger-service-image:latest
    ports:
      - 80:8080
    container_name: userservice
    hostname: userservice
    networks:
      - auctionnetwork

networks:
  auctionnetwork:
    name: auctionnetwork
    external: true

