version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27019:27017
    container_name: mongodb
    hostname: mongodb
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - auctionnetwork

  authenticationservice:
    image: rasmusdd/authenticationservice-image:1.0.0
    ports:
      - 82:8080
    depends_on:
      - mongodb
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Bruger
      - vaultConnectionString=https://vault_dev:8201
    container_name: authenticationservice
    hostname: authenticationservice
    networks:
      - auctionnetwork
    command: ["/bin/sh", "-c", "sleep 20 && dotnet Authentication.dll"]

  userservice:
    image: jakobhaulund/bruger-service-image:1.0.0
    ports:
      - 80:8080
    depends_on:
      - mongodb
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Bruger
    container_name: userservice
    hostname: userservice
    networks:
      - auctionnetwork

networks:
  auctionnetwork:
    name: auctionnetwork
    external: true

volumes:
  mongodb_data_container:
